---
- name: clone fdk-aac source
  git: repo=git://git.code.sf.net/p/opencore-amr/fdk-aac depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/fdk-aac force=yes

- name: clean the fdk-aac repo
  shell: cd {{ ffmpeg_path }}/fdk-aac && autoreconf -fiv

- name: configure fdk-aac
  shell: cd {{ ffmpeg_path }}/fdk-aac && ./configure --disable-shared creates={{ ffmpeg_path }}/fdk-aac/Makefile

- name: make fdk-aac
  shell: cd {{ ffmpeg_path }}/fdk-aac && make 

- name: install fdk-aac
  sudo: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make install

- name: clean the fkd-aac repo
  sudo: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make distclean