---
- name: clone libvpx source
  git: repo=https://chromium.googlesource.com/webm/libvpx.git depth=1 dest={{ ffmpeg_path }}/libvpx force=yes

- name: configure libvpx
  shell: cd {{ ffmpeg_path }}/libvpx && ./configure --disable-examples creates={{ ffmpeg_path }}/libvpx/Makefile

- name: make libvpx
  shell: cd {{ ffmpeg_path }}/libvpx && make 

- name: install libvpx
  sudo: yes
  shell: cd {{ ffmpeg_path }}/libvpx && make install

- name: clean the libvpx repo
  sudo: yes
  shell: cd {{ ffmpeg_path }}/libvpx && make distclean