---
- name: Check if nux repo is already configured.
  stat: path={{ nux_repofile_path }}
  register: nux_repofile_result

- name: Import NUX GPG key.
  rpm_key:
    key: "{{ nux_repo_gpg_key_url }}"
    state: present
  when: not nux_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install nux repo.
  yum:
    name: "{{ nux_repo_url }}"
    state: present
  register: result
  # until: '"failed" not in result'
  # retries: 5
  # delay: 10
  # when: not nux_repofile_result.stat.exists

- name: Install ffmpeg
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
    enablerepo: nux-dextop
  with_items:
    - ffmpeg
    - ffmpeg-devel

# ---
# # can I add a check here that if ffmpeg is already configured and installed
# # I skip the whole rest of the role?
# - include: ff_libraries.yml
# - include: yasm.yml
# - include: x264.yml
# - include: libfdk_aac.yml
# - include: libmp3lame.yml
# - include: libopus.yml
# - include: libogg.yml
# - include: libvorbis.yml
# - include: libvpx.yml
# - include: ffmpeg.yml
