notifications:
  email: false

rvm:
  - 2.2.4
  - 2.1.8

notifications:
  irc: "irc.freenode.org#blacklight"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby

script:
  - bundle exec rake
