#!/bin/bash

while read uri; do
  saveIFS=$IFS
  IFS='=&'
  parm=($uri)
  IFS=$saveIFS
  raw=`wget -O - "http://localhost/authorize.txt?token=${parm[1]}" 2>/dev/null`
  resp="${raw//[[:space:]]/}"
  valid=`echo ${parm[1]} | grep ^${resp}`
  if [ -n "${valid}" ] && [ -n "${resp}" ]; then
    echo $uri
  else
    echo "/streams/forbidden"
  fi
done