require: rubocop-rspec

AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'app/services/tei_converter.rb'
    - 'lib/import/text_importer.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/services/tei_converter.rb'
    - 'lib/import/text_importer.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/tei_converter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/tei_converter.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/Semicolon:
  Exclude:
    - 'spec/**/*'

Style/Lambda:
  Exclude:
    - 'spec/**/*'

Style/GlobalVars:
  Exclude:
    # - 'spec/**/*'
    # - 'spec/jobs/event_jobs_spec.rb'
    # - 'curation_concerns-models/lib/generators/curation_concerns/models/templates/config/redis_config.rb'
    # - 'curation_concerns-models/lib/curation_concerns/models/active_record/redis.rb'
    - 'config/initializers/redis_config.rb'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'bin/*'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/*'

# Style/HashSyntax:
#   Exclude:
#     - 'lib/generators/curation_concerns/templates/catalog_controller.rb'

# Style/SingleLineBlockParams:
#   Enabled: false

# Style/SignalException:
#   Enabled: false

# Rails/Date:
#   Enabled: false
#
# Rails/TimeZone:
#   Enabled: false
Rails/Output:
  Exclude:
    - 'lib/import/text_importer.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

# RSpec/FilePath:
#   Enabled: false
#
# RSpec/InstanceVariable:
#   Enabled: false

RSpec/DescribeClass:
  Exclude:
     - 'spec/features/**/*'
#     - 'spec/views/**/*'
#     - 'spec/routing/**/*'
#     - 'spec/inputs/**/*'
#
# RSpec/DescribedClass:
#   Exclude:
#     - 'spec/actors/curation_concerns/manages_embargoes_actor_spec.rb'
