language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2
jdk:
  - oraclejdk8
before_script:
  - "bin/setup"

notifications:
  email:
    - justin@curationexperts.com

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
