---
- name: ensure valid hostname
  debug: msg="{{ ansible_hostname }}"

# - name: disable firewalld temporarily # create service from avalon-ip-tables.sh
#   become: true
#   service: name=firewalld state=stopped

- name: disable SELinux
  become: true
  selinux: conf=/etc/selinux/config state=disabled

- name: install the development tools package group
  become: true
  yum: name="@Development tools" state=present

- name: install Maven
  become: true
  yum: name="maven" state=present

- name: grant temporary permissions for {{ remote_user }} on opt directory
  become: true
  file: path=/opt owner={{ remote_user }} group={{ remote_user }}
...
