---
#- name: check ruby {{ ruby_version }} installed
#  shell: "ruby -v | grep {{ ruby_version }}"
#  register: ruby_installed
#  changed_when: false
#  ignore_errors: yes # failure means our ruby version isn't installed yet
#  always_run: yes

- name: remove package ruby
  sudo: yes
  yum: name=ruby state=absent

- name: download ruby
  get_url: url=https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.8.tar.gz owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} dest={{ install_path }}/ruby-2.3.8.tar.gz validate_certs=False

- name: unzip ruby file
  unarchive: src={{ install_path }}/ruby-2.3.8.tar.gz dest={{ install_path }}/ creates={{ install_path }}/ruby-2.3.8/compile.c copy=no

- name: check if ruby is installed
  sudo: yes
  stat: path=/usr/local/bin/ruby
  register: ruby

- name: configure ruby
  shell: cd {{ install_path }}/ruby-2.3.8 && ./configure --enable-shared creates={{ install_path }}/ruby-2.3.8/Makefile

- name: make ruby
  shell: cd {{ install_path }}/ruby-2.3.8 && make
  when: ruby.stat.exists == False

- name: install ruby
  sudo: yes
  shell: cd {{ install_path }}/ruby-2.3.8 && make install creates=/usr/local/bin/ruby
  when: ruby.stat.exists == False

- name: symlink ruby for root
  sudo: yes
  file: src=/usr/local/bin/ruby dest=/usr/bin/ruby state=link

- name: symlink gem for root
  sudo: yes
  file: src=/usr/local/bin/gem dest=/usr/bin/gem state=link

- name: install bundler
  sudo: yes
  gem: name=bundler user_install=no state=present
