---
# the rest of the imagemagick role is now exactly the same as the ubuntu version
# to integrate, we should be able to use the distro-neutral package approach
# with Ansible 2.0
- name: install IM libraries
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
      - fontconfig-devel
      - freetype-devel
      - libtool-ltdl-devel
      - libpng-devel
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - libtool
      - make
      - mercurial
      - pkgconfig
      - zlib-devel
      - lcms2-devel

- name: remove package imagemagick
  sudo: yes
  yum: name=imagemagick state=absent

- name: create IM sources dir
  sudo: yes
  file: owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory path={{ magick_path }}

- name: IM add ldconfig for /usr/local/lib
  sudo: yes
  copy: dest=/etc/ld.so.conf.d/usr-local.conf content=/usr/local/lib owner=root group=root mode=0644 
