---
- name: download fedora
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/4.4.0/fcrepo-webapp-4.4.0.war owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} dest={{ install_path }}/fcrepo-webapp-4.4.0.war

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  sudo: yes

- name: check fedora.war
  stat: path=/var/lib/tomcat/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  sudo: yes
  command: cp {{ install_path }}/fcrepo-webapp-4.4.0.war /var/lib/tomcat/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  sudo: yes
  template: src=tomcat.j2 dest=/etc/tomcat/tomcat.conf backup=yes 
# TODO: make Java options configurable at the time of the ansible run

- name: restart tomcat
  sudo: yes
  service: name=tomcat enabled=yes state=restarted
