---
- name: ensure valid hostname
  debug: msg="{{ ansible_hostname }}"

- name: disable firewalld temporarily # create service from avalon-ip-tables.sh
  become: true
  service: name=firewalld state=stopped

- name: disable SELinux
  become: true
  selinux: conf=/etc/selinux/config state=disabled

- name: install the development tools package group
  become: true
  yum: name="@Development tools" state=present

- name: install the epel repository
  become: true
  yum: name="epel-release" state=present

- name: download Nux Dextop repository
  get_url: url=http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm dest={{ install_path }}/ force=no

- name: add Nux Dextop repository
  become: true
  command: rpm -ivh nux-dextop-release-0-5.el7.nux.noarch.rpm

- name: disable Nux Dextop repository
  become: true
  replace: dest=/etc/yum.repos.d/nux-dextop.repo regexp="enabled=1" replace="enabled=0" backup=yes

- name: add nul-public repository
  become: true
  copy: src=nul-public.repo dest=/etc/yum.repos.d

- name: disable nul-public repository
  become: true
  replace: dest=/etc/yum.repos.d/nul-public.repo regexp="enabled=1" replace="enabled=0" backup=yes

- name: add nul-public gpg key
  become: true
  command: curl http://yumrepo-public.library.northwestern.edu/RPM-GPG-KEY-nul -o /etc/pki/rpm-gpg/RPM-GPG-KEY-nul

- name: grant temporary permissions for {{ remote_user }} on opt directory
  become: true
  file: path=/opt owner={{ remote_user }} group={{ remote_user }}
...
