---
- name: install mariadb server
  become: true
  yum: name=mariadb-server state=present

- name: change mariadb defaults
  become: true
  lineinfile: dest="/etc/my.cnf.d/{{ item.file }}" insertafter="{{ item.insertafter }}" line="{{ item.line }}" state=present backup=yes
  with_items:
    - { file: client.cnf,        insertafter: '^\[client\]', line: default-character-set = utf8 }
    - { file: mysql-clients.cnf, insertafter: '^\[mysql\]' , line: default-character-set = utf8 }
    - { file: server.cnf,        insertafter: '^\[mysqld\]', line: default-storage-engine = innodb }
    - { file: server.cnf,        insertafter: '^\[mysqld\]', line: character-set-server = utf8 }
    - { file: server.cnf,        insertafter: '^\[mysqld\]', line: "init-connect = 'SET NAMES utf8'" }
    - { file: server.cnf,        insertafter: '^\[mysqld\]', line: collation-server = utf8_unicode_ci }

- name: start mariadb service
  become: true
  service: name=mariadb state=started

- name: set mariadb root password
  become: true
  command: /usr/bin/mysqladmin -u root -h localhost password '{{ maria_pass }}'

- name: create fedora3 database
  command: mysql -u root --password={{ maria_pass }} -e "CREATE DATABASE {{ maria_avalon_fedora_db }}"
  
- name: create fcrepo user
  command: mysql -u root --password={{ maria_pass }} -e "CREATE USER '{{ maria_avalon_fedora_user }}'@'localhost' IDENTIFIED BY '{{ maria_avalon_fedora_pass }}'"

- name: grant fcrepo privileges on fedora3
  command: mysql -u root --password={{ maria_pass }} -e "GRANT ALL PRIVILEGES ON {{ maria_avalon_fedora_db }}.* TO '{{ maria_avalon_fedora_user }}'@'localhost'"
  
- name: create rails database
  command: mysql -u root --password={{ maria_pass }} -e "CREATE DATABASE {{ maria_avalon_rails_db }}"

- name: create rails user
  command: mysql -u root --password={{ maria_pass }} -e "CREATE USER '{{ maria_avalon_rails_user }}'@'localhost' IDENTIFIED BY '{{ maria_avalon_rails_pass }}'"

- name: grant rails privileges on rails
  command: mysql -u root --password={{ maria_pass }} -e "GRANT ALL PRIVILEGES ON {{ maria_avalon_rails_db }}.* TO '{{ maria_avalon_rails_user }}'@'localhost'"
  
- name: flush privileges
  command: mysql -u root --password={{ maria_pass }} -e "FLUSH PRIVILEGES"
...
