---
- name: install passenger package requirements
  become: true
  yum: name={{ item }} state=present
  with_items:
    - libcurl-devel
    - httpd-devel

- name: install rack (<2.0.0 for ruby 2.1.7 and passenger 5.0.17)
  become: true
  gem: name=rack user_install=no state=present version=1.6.4

- name: install passenger gem
  become: true
  gem: name=passenger user_install=no state=present version={{ passenger_version }}

- name: symlink passenger utilities for root user
  become: true
  file: src=/usr/local/bin/{{ item }} dest=/usr/sbin/{{ item }} state=link
  with_items:
      - passenger
      - passenger-config
      - passenger-install-apache2-module
      - passenger-install-nginx-module
      - passenger-memory-stats
      - passenger-status

- name: install passenger-install-apache2-module
  become: true
  shell: passenger-install-apache2-module --auto creates=/usr/local/lib/ruby/gems/{{ ruby_version }}/gems/passenger-{{ passenger_version }}/buildout/apache2/mod_passenger.so 

- name: generate passenger.conf file
  become: true
  shell: passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf creates=/etc/httpd/conf.d/passenger.conf

- name: place the avalon passenger configuration file
  become: true
  copy: src=passenger.conf dest=/etc/httpd/conf.d/passenger.conf backup=yes
  
- name: restart apache
  become: true
  service: name=httpd state=restarted
...
