---
# adapted from
# https://github.com/akishin/ansible-playbooks/blob/master/lokka/roles/passenger/tasks/main.yml

- name: install passenger gem
  gem: name=passenger user_install=no state=present version={{ passenger_ver }}

- name: symlink passenger utilities for root user
  file: src=/usr/local/bin/{{ item }} dest=/usr/sbin/{{ item }} state=link
  with_items:
      - passenger
      - passenger-config
      - passenger-install-apache2-module
      - passenger-install-nginx-module
      - passenger-memory-stats
      - passenger-status

- name: install passenger-install-apache2-module
  sudo: yes
  shell: passenger-install-apache2-module --auto creates=/usr/local/lib/ruby/gems/{{ ruby_ver }}/gems/passenger-{{ passenger_ver }}/buildout/apache2/mod_passenger.so 

- name: generate passenger.conf file
  shell: passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf creates=/etc/httpd/conf.d/passenger.conf
  
- name: restart apache
  service: name=httpd state=restarted
  