#!/usr/bin/env ruby

type = ARGV[0]  # audio, video, image, text, document
dc_file = ARGV[1]

unless type && dc_file
  $stderr.puts "Usage: #{$PROGRAM_NAME} <type of work> <path to Dublin Core XML file>"
  exit 1
end

type = type.downcase

puts "Type of work: #{type}"
puts "Dublin Core file: #{dc_file}"

puts "Loading environment..."
require File.expand_path('../../config/environment',  __FILE__)
require 'import'

puts "Starting #{type} import..."
count = Import::Importer.new(type, dc_file).run

puts "Imported #{count} #{type} records."

