#!/usr/bin/env ruby

dir = ARGV[0]  # Directory where TEI files are located

unless dir
  $stderr.puts "Usage: #{$PROGRAM_NAME} <path to directory with TEI files>"
  exit 1
end

puts "Import Text records using TEI files in: #{dir}"

puts "Loading environment"
require File.expand_path('../../config/environment',  __FILE__)
require 'import'

puts "Starting import"
importer = Import::TextImporter.new(dir)
importer.run

puts "Printing import results"

unless importer.skipped_imports.empty?
  puts "\nSkipped Imports:"
  importer.skipped_imports.each { |msg| puts "  #{msg}" }
end

unless importer.warnings.empty?
  puts "\nWarning messages:"
  importer.warnings.each { |msg| puts msg }
end

unless importer.errors.empty?
  puts "\nError messages:"
  importer.errors.each { |msg| puts msg }
end

puts "\nImport finished:"
puts "   Records imported: #{importer.successful_imports.count}"
puts "   Records skipped:  #{importer.skipped_imports.count}"
puts "   Warnings:         #{importer.warnings.count}"
puts "   Errors:           #{importer.errors.count}"

