# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include OnCampusAccess

  def human_readable_type
    'File'
  end
end
